---
driver:
  name: vagrant
  vm_hostname: linux.ci.local
  use_sudo: false
  customize:
    memory: 1024


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: linux
  grains:
    noservices: true
  state_top:
    base:
      "*":
        - linux
  pillars:
    top.sls:
      base:
        "*":
          - linux

platforms:
- name: ubuntu-16.04
- name: ubuntu-14.04
- name: centos-7.3
- name: centos-6.8

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
